// This file was autogenerated by node_modules/closure-library//closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/Animation.js', ['animatejs.Animation'], []);
goog.addDependency('../../../../src/namespace.js', ['animatejs'], ['animatejs.Animation']);
